### ISSUE TITLE
accauracy don't change

### ISSUE THREAD

**Issue by nbilyana80** [adityajn105/tumor-segmentation-unet#1]
I have tested your code, but the accuracy don't change during all Epochs:
902/4902 [==============================] - 62s 13ms/step - loss: 1.0887 - acc: 0.9696 - iou_metric: 4.0159e-04 - val_loss: 1.0708 - val_acc: 0.9821 - val_iou_metric: 1.2325e-14

Epoch 00001: val_loss improved from inf to 1.07076, saving model to model_best_checkpoint.h5
Epoch 2/100
4902/4902 [==============================] - 53s 11ms/step - loss: 1.0688 - acc: 0.9826 - iou_metric: 1.1319e-14 - val_loss: 1.0708 - val_acc: 0.9821 - val_iou_metric: 1.2325e-14

Epoch 00002: val_loss improved from 1.07076 to 1.07076, saving model to model_best_checkpoint.h5
Epoch 3/100
4902/4902 [==============================] - 53s 11ms/step - loss: 1.0688 - acc: 0.9826 - iou_metric: 1.1325e-14 - val_loss: 1.0708 - val_acc: 0.9821 - val_iou_metric: 1.2325e-14

Epoch 00003: val_loss improved from 1.07076 to 1.07076, saving model to model_best_checkpoint.h5
Epoch 4/100
4902/4902 [==============================] - 53s 11ms/step - loss: 1.0688 - acc: 0.9826 - iou_metric: 1.1320e-14 - val_loss: 1.0708 - val_acc: 0.9821 - val_iou_metric: 1.2325e-14

Epoch 00004: val_loss improved from 1.07076 to 1.07076, saving model to model_best_checkpoint.h5
Epoch 5/100
4902/4902 [==============================] - 53s 11ms/step - loss: 1.0688 - acc: 0.9826 - iou_metric: 1.1309e-14 - val_loss: 1.0708 - val_acc: 0.9821 - val_iou_metric: 1.2325e-14

Epoch 00005: val_loss improved from 1.07076 to 1.07076, saving model to model_best_checkpoint.h5
Epoch 6/100
4902/4902 [==============================] - 53s 11ms/step - loss: 1.0688 - acc: 0.9826 - iou_metric: 1.1248e-14 - val_loss: 1.0708 - val_acc: 0.9821 - val_iou_metric: 1.2325e-14

Epoch 00006: val_loss did not improve from 1.07076
Epoch 7/100
4902/4902 [==============================] - 53s 11ms/step - loss: 1.0688 - acc: 0.9826 - iou_metric: 1.1315e-14 - val_loss: 1.0708 - val_acc: 0.9821 - val_iou_metric: 1.2325e-14

**Comment by adityajn105** [comment]
Run google-colab notebook using the below link and check the output. I am getting correct results.

[https://colab.research.google.com/drive/1FHAzVJJJreuXwdTrlvM6MQinOTwr0jW7](https://colab.research.google.com/drive/1FHAzVJJJreuXwdTrlvM6MQinOTwr0jW7)

Compare your implementation and see what's wrong.
